version: '3.8'
services:
  api:
    build: .
    depends_on:
      - pg
    ports:
      - 8000:8000
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --reload"
    volumes:
      - ./:/app/

  pg:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5 
  
  test:
    build: .
    depends_on:
      - pg
      - api
    command: >
      sh -c "export SQLALCHEMY_SILENCE_UBER_WARNING=1 && pytest -vv"
