version: '3.9'
services:
  api:
    build: .
    networks:
      - network_menu
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - 8000:8000
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  pg:
    image: postgres:15.1-alpine
    networks:
      - network_menu
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    # volumes:
    #   - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server
    networks:
      - network_menu
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network_menu:
